services:
    estructura:
        image: sysacad-backend:v1.0.0
        networks:
          - mynetwork
        ports:
          - 5000:5000
        environment:
          - FLASK_CONTEXT=${FLASK_CONTEXT}
          - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}  
          - SQLALCHEMY_RECORD_QUERIES=${SQLALCHEMY_RECORD_QUERIES}
          - PROD_DATABASE_URI=${PROD_DATABASE_URI}
        env_file:
          - ../.env
    redis:
        image: redis:latest
        container_name: redis
        ports:
          - "6379:6379"
        networks:
          - mynetwork
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
          POSTGRES_USER: sysacad_user
          POSTGRES_PASSWORD: sysacad_password
          POSTGRES_DB: sysacad_db
        ports:
          - "5433:5432"
        networks:
          - mynetwork
networks:
    mynetwork:
        external: true
